# Generated by Django 4.2.4 on 2023-08-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='Platos',
        ),
    ]
