# Generated by Django 4.2.4 on 2023-08-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_remove_platos_imagen_remove_platos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='platos/'),
        ),
        migrations.AddField(
            model_name='platos',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
