# Generated by Django 4.2.4 on 2023-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_platos_imagen_platos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='imagen',
            field=models.ImageField(null='True', upload_to='platos'),
        ),
    ]
