# Generated by Django 4.2.4 on 2023-09-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_platosinicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatosInicio',
        ),
    ]
